exit.5.14.id=toLevel1_r1_c0_right
exit.5.14.direction=RIGHT
exit.5.14.type=ROOM
exit.5.14.requiresKey=true
exit.5.14.requiresEnemies=false
exit.5.14.doorStateId=level1_link_r1c0_r1c1
exit.5.14.visualId=east
