exit.1.8.id=toLevel1_r2_c2_up
exit.1.8.direction=UP
exit.1.8.type=ROOM
exit.1.8.requiresKey=true
exit.1.8.requiresEnemies=false
exit.1.8.doorStateId=level1_link_r1c2_r2c2
exit.1.8.visualId=north

exit.5.1.id=toLevel1_r2_c2_left
exit.5.1.direction=LEFT
exit.5.1.type=ROOM

exit.5.14.id=toLevel1_r2_c2_right
exit.5.14.direction=RIGHT
exit.5.14.type=ROOM
