exit.1.8.id=toLevel1_r2_c1_up
exit.1.8.direction=UP
exit.1.8.type=ROOM
exit.1.8.requiresKey=true
exit.1.8.requiresEnemies=false
exit.1.8.doorStateId=level1_link_r1c1_r2c1
exit.1.8.visualId=north

exit.5.14.id=toLevel1_r2_c1_right
exit.5.14.direction=RIGHT
exit.5.14.type=ROOM
