exit.5.1.id=toLevel1_r1_c1_left
exit.5.1.direction=LEFT
exit.5.1.type=ROOM
exit.5.1.requiresKey=true
exit.5.1.requiresEnemies=false
exit.5.1.doorStateId=level1_link_r1c0_r1c1
exit.5.1.visualId=west

exit.5.14.id=toLevel1_r1_c1_right
exit.5.14.direction=RIGHT
exit.5.14.type=ROOM

exit.9.8.id=toLevel1_r1_c1_down
exit.9.8.direction=DOWN
exit.9.8.type=ROOM
exit.9.8.requiresKey=true
exit.9.8.requiresEnemies=false
exit.9.8.doorStateId=level1_link_r1c1_r2c1
exit.9.8.visualId=south
