exit.5.1.id=toLevel1_r0_c3_left
exit.5.1.direction=LEFT
exit.5.1.type=ROOM
exit.5.1.requiresKey=true
exit.5.1.requiresEnemies=false
exit.5.1.doorStateId=level1_link_r0c2_r0c3
exit.5.1.visualId=west

exit.9.8.id=toLevel1_r0_c3_down
exit.9.8.direction=DOWN
exit.9.8.type=ROOM
