package jzelda.model;

/**
 * Lightweight transient visual feedback generated by the model and rendered by
 * the view, such as item collection text, damage flashes and transitions.
 */
public class VisualEffect {
    private final String text;
    private final double x;
    private final double y;
    private final long totalMs;
    private long remainingMs;

    /**
     * Creates an effect.
     *
     * @param text text label
     * @param x x coordinate
     * @param y y coordinate
     * @param durationMs duration in milliseconds
     */
    public VisualEffect(String text, double x, double y, long durationMs) {
        this.text = text;
        this.x = x;
        this.y = y;
        this.totalMs = durationMs;
        this.remainingMs = durationMs;
    }

    /**
     * Updates remaining lifetime.
     *
     * @param deltaMs elapsed milliseconds
     */
    public void update(long deltaMs) {
        remainingMs -= Math.max(0, deltaMs);
    }

    /**
     * @return {@code true} while the effect should be rendered
     */
    public boolean isAlive() {
        return remainingMs > 0;
    }

    /**
     * @return effect label
     */
    public String getText() {
        return text;
    }

    /**
     * @return x coordinate
     */
    public double getX() {
        return x;
    }

    /**
     * @return y coordinate
     */
    public double getY() {
        return y;
    }

    /**
     * @return animation progress between {@code 0.0} and {@code 1.0}
     */
    public double getProgress() {
        return totalMs <= 0 ? 1.0 : 1.0 - (remainingMs / (double) totalMs);
    }
}
